/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import com.sun.prism.j2d.J2DPipeline;
import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoMedicacao;
import fatec.poo.control.DaoMedico;
import fatec.poo.control.DaoPaciente;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Medico;
import fatec.poo.model.Paciente;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author LucasMorais
 */
public class GuiConsulta extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    
    private DaoConsulta daoConsulta;
    private DaoPaciente daoPaciente;
    private DaoMedico daoMedico;
    private Consulta consulta;
    private Paciente paciente;
    private Medico medico;
    private PreparaConexao prepCon;
 
    public GuiConsulta() {
        initComponents();
        aplicarMascaraNoCPFMedico();
        aplicarMascaraNoCPFPaciente();
        aplicarMascaraNaData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblData = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        txtCPFMedico = new javax.swing.JFormattedTextField();
        btnInserir = new javax.swing.JButton();
        txtCPFPaciente = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        lblCodigo = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblCPFMedico = new javax.swing.JLabel();
        btnConsultarMedico = new javax.swing.JButton();
        btnConsultarPaciente = new javax.swing.JButton();
        lblCPFPaciente = new javax.swing.JLabel();
        lblNomeMedico = new javax.swing.JLabel();
        lblNomePaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblData.setText("Data");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblValor.setText("Valor");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        txtCPFMedico.setText("   .   .   -");
        txtCPFMedico.setEnabled(false);

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        txtCPFPaciente.setText("   .   .   -");
        txtCPFPaciente.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtData.setEnabled(false);

        lblCodigo.setText("Código");

        txtValor.setEnabled(false);

        lblCPFMedico.setText("CPF Médico");

        btnConsultarMedico.setText("...");
        btnConsultarMedico.setEnabled(false);
        btnConsultarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMedicoActionPerformed(evt);
            }
        });

        btnConsultarPaciente.setText("...");
        btnConsultarPaciente.setEnabled(false);
        btnConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPacienteActionPerformed(evt);
            }
        });

        lblCPFPaciente.setText("CPF Paciente");

        lblNomeMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNomeMedico.setEnabled(false);

        lblNomePaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNomePaciente.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPFPaciente)
                            .addComponent(lblData)
                            .addComponent(lblValor)
                            .addComponent(lblCPFMedico)
                            .addComponent(lblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPFMedico)
                            .addComponent(txtCPFPaciente)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnConsultarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnConsultarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(lblNomeMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFMedico)
                    .addComponent(txtCPFMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarMedico)
                    .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFPaciente)
                    .addComponent(txtCPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPaciente)
                    .addComponent(lblNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    
    
    private void limparForms(){
       txtCPFMedico.setText("");
       txtCPFPaciente.setText("");
       txtCodigo.setText("");
       txtData.setText("");
       lblNomeMedico.setText("");
       lblNomePaciente.setText("");
       txtValor.setText("");
    }
    
    private void aplicarMascaraNoCPFMedico(){
        try {
            MaskFormatter mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraCPF.setPlaceholderCharacter('_');
            mascaraCPF.install(txtCPFMedico);
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void aplicarMascaraNoCPFPaciente(){
     try {
            MaskFormatter mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraCPF.setPlaceholderCharacter('_');
            mascaraCPF.install(txtCPFPaciente);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void aplicarMascaraNaData(){
        try {
            MaskFormatter mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
            mascaraData.install(txtData);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Confirma a exclusão?")==0){
            daoConsulta.excluirConsulta(consulta);
        }
        btnConsultar.setEnabled(true);
        txtCodigo.setEnabled(true);
        txtCodigo.setFocusable(true);
        txtCPFMedico.setEnabled(false);
        btnConsultarMedico.setEnabled(false);
        txtCPFPaciente.setEnabled(false);
        btnConsultarPaciente.setEnabled(false);
        txtData.setEnabled(false);
        txtValor.setEnabled(false);
        limparForms();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Confirma a alteração?")==0){
            consulta = new Consulta(consulta.getCodigo(), txtData.getText());
            consulta.setValor(Double.parseDouble(txtValor.getText()));
            daoConsulta.alterarConsulta(consulta);
        }
        btnConsultar.setEnabled(true);
        txtCodigo.setEnabled(true);
        txtCodigo.setFocusable(true);
        txtCPFMedico.setEnabled(false);
        btnConsultarMedico.setEnabled(false);
        txtCPFPaciente.setEnabled(false);
        btnConsultarPaciente.setEnabled(false);
        txtData.setEnabled(false);
        txtValor.setEnabled(false);
        limparForms();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        consulta = new Consulta(Integer.parseInt(txtCodigo.getText()), txtData.getText());
        consulta.setValor(Double.parseDouble(txtValor.getText()));
        paciente.addConsulta(consulta);
        consulta.setMedico(medico);
        medico.addConsulta(consulta);
        daoConsulta.inserirConsulta(consulta, paciente);
        limparForms();  

    }//GEN-LAST:event_btnInserirActionPerformed
    
    
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int codConsulta = Integer.parseInt(txtCodigo.getText());
        paciente = null;
        consulta = null;
        consulta = daoConsulta.consultarConsulta(codConsulta);
       
        if(consulta == null){
            btnInserir.setEnabled(true);
            txtCPFMedico.setEnabled(true);
            btnConsultarMedico.setEnabled(true);
        }
        else{
            btnConsultar.setEnabled(false);
            txtCodigo.setEnabled(false);
            paciente = daoConsulta.consultarPaciente(codConsulta);
            txtCPFMedico.setText(consulta.getMedico().getCpf());
            lblNomeMedico.setText(consulta.getMedico().getNome());
            txtCPFPaciente.setText(paciente.getCpf());
            lblNomePaciente.setText(paciente.getNome());
            txtData.setText(consulta.getData());
            txtValor.setText(String.valueOf(consulta.getValor()));
            txtData.setEnabled(true);
            txtValor.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsultarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMedicoActionPerformed
        String cpfMedico = txtCPFMedico.getText().replace(".", "").replace("-", "");
        medico = daoMedico.consultarMedico(cpfMedico);
        if(medico==null){
            JOptionPane.showMessageDialog(null, "Medico não cadastrado!");
        }
        else{
            lblNomeMedico.setText(medico.getNome());
            btnConsultarMedico.setEnabled(false);
            txtCPFMedico.setEnabled(false);
            txtCPFPaciente.setEnabled(true);
            btnConsultarPaciente.setEnabled(true);
        }

    }//GEN-LAST:event_btnConsultarMedicoActionPerformed

    private void btnConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPacienteActionPerformed
        String cpfPaciente = txtCPFPaciente.getText().replace(".", "").replace("-", "");
        paciente = daoPaciente.consultarPaciente(cpfPaciente);
        if(paciente==null){
            JOptionPane.showMessageDialog(null, "Paciente não cadastrado!");
        }
        else{
            lblNomePaciente.setText(paciente.getNome());
            txtCPFPaciente.setEnabled(false);
            btnConsultarPaciente.setEnabled(false);
            txtData.setEnabled(true);
            txtValor.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarPacienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prepCon = new PreparaConexao("","");                      
        prepCon.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        prepCon.setConnectionString("jdbc:ucanaccess://C:\\\\Users\\\\LucasMorais\\\\Desktop\\\\Trabalhos POO\\\\src\\\\fatec\\\\poo\\\\basededados\\\\BDClinicaEricaLucasNicolas.accdb");
        daoMedico = new DaoMedico(prepCon.abrirConexao());
        daoPaciente = new DaoPaciente(prepCon.abrirConexao());
        daoConsulta = new DaoConsulta(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarMedico;
    private javax.swing.JButton btnConsultarPaciente;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCPFMedico;
    private javax.swing.JLabel lblCPFPaciente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblValor;
    private javax.swing.JFormattedTextField txtCPFMedico;
    private javax.swing.JFormattedTextField txtCPFPaciente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
