/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoExame;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Exame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author LucasMorais
 */
public class GuiExame extends javax.swing.JFrame {

    /**
     * Creates new form GuiExame
     */
    public GuiExame() {
        initComponents();
        aplicarMascaraNaData();
    }
    
    private DaoExame daoExame = null;
    private DaoConsulta daoConsulta = null;
    private Exame exame = null;
    private Consulta consulta = null;
    private PreparaConexao prepCon = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblCodigoConsulta = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCodigoConsulta = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtHorario = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnConsultarConsulta = new javax.swing.JButton();
        lblCodigoConsulta1 = new javax.swing.JLabel();
        lblNomeMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marcar Exame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblCodigo.setText("Código");

        lblCodigoConsulta.setText("Código Consulta");

        lblDescricao.setText("Descrição");

        lblData.setText("Data");

        lblHorario.setText("Horário");

        lblValor.setText("Valor");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtCodigoConsulta.setEnabled(false);

        txtDescricao.setEnabled(false);

        txtData.setText("/   /");
        txtData.setEnabled(false);

        txtHorario.setEnabled(false);

        txtValor.setEnabled(false);

        btnConsultarConsulta.setText("...");
        btnConsultarConsulta.setEnabled(false);
        btnConsultarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarConsultaActionPerformed(evt);
            }
        });

        lblCodigoConsulta1.setText("Médico");

        lblNomeMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNomeMedico.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCodigoConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar)
                                .addGap(18, 18, 18)
                                .addComponent(btnInserir)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCodigoConsulta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addComponent(lblData)
                            .addComponent(lblHorario)
                            .addComponent(lblValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHorario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoConsulta)
                    .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarConsulta)
                    .addComponent(lblCodigoConsulta1)
                    .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarMascaraNaData(){
        try {
            MaskFormatter mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
            mascaraData.install(txtData);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int codExame = Integer.parseInt(txtCodigo.getText());
        exame = daoExame.consultarExame(codExame);
        if(exame == null){
            txtCodigoConsulta.setEnabled(true);
            btnConsultarConsulta.setEnabled(true); 
            btnInserir.setEnabled(true);
            btnConsultar.setEnabled(false);    
         
        }
        else{
            consulta = daoConsulta.consultarConsulta(exame.getConsulta().getCodigo());
            txtCodigoConsulta.setText(String.valueOf(consulta.getCodigo()));
            txtDescricao.setText(exame.getDescricao());
            txtData.setText(exame.getData());
            txtHorario.setText(exame.getHorario());
            txtValor.setText(String.valueOf(exame.getValor()));
            lblNomeMedico.setText(consulta.getMedico().getNome());
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            
            txtDescricao.setEnabled(true);
            txtData.setEnabled(true);
            txtHorario.setEnabled(true);
            txtValor.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    
    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        exame = new Exame(Integer.parseInt(txtCodigo.getText()), txtDescricao.getText());
        exame.setConsulta(consulta);
        
        exame.setData(txtData.getText());
        exame.setHorario(txtHorario.getText());
        exame.setValor(Double.parseDouble(txtValor.getText()));
            
        daoExame.inserirExame(exame);
        consulta.addExame(exame);    
        
        btnInserir.setEnabled(false);
        btnConsultar.setEnabled(true);
        txtCodigo.setEnabled(true);
        txtCodigo.setFocusable(true);
        txtCodigoConsulta.setEnabled(false);
        txtData.setEnabled(false);
        txtDescricao.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);
        limparForms();
         
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){
            
            /*OBS: Como a modelagem deixa explicita que a classe "EXAME" não possui setDescrição, sendo essa unicamente feita
            através do método construtor do exame, sendo assim necessário criar um novo Exame provisório que coleta o código do exame
            atualmente em contexto (o que foi coletado com o ConsultarExame). Após isso eu faço uma atualização do exame em contexto
            this.exame = exameParaAlterar.
            
            Assim não fere a modelagem, e não fere o que foi solicitado:
            "Na gui Marcar Exame, na operação de alteração, somente a descrição, data, horário e valor do 
exame       podem ser alterados."
            */
            Exame exameParaAlterar = new Exame(exame.getCodigo(), txtDescricao.getText());
           
            exameParaAlterar.setConsulta(consulta); //evitar NullPointerException mantendo a consulta atual. O DaoExame vai ignorar isso no método alterar.
            exameParaAlterar.setData(txtData.getText());
            exameParaAlterar.setHorario(txtHorario.getText());
            exameParaAlterar.setValor(Double.parseDouble(txtValor.getText()));
            daoExame.alterarExame(exameParaAlterar);
            
            /*Mantendo a associação binária conforme visto no exemplo prjExemplo_OO_BD_Parte_2
            No arquivo GuiFuncionarioHorista na função de alterar.*/
           
            consulta.addExame(exameParaAlterar);
            JOptionPane.showMessageDialog(this, "Alterado com sucesso.");
            limparForms();
        }
     
        btnConsultar.setEnabled(true);
        txtCodigo.setEnabled(true);
        txtCodigo.setFocusable(true);
        txtCodigoConsulta.setEnabled(false);
        txtData.setEnabled(false);
        txtDescricao.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        limparForms();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Confirma exclusão?")==0){
            daoExame.excluirExame(exame);
        }
        
        btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtCodigo.setEnabled(true);
        txtCodigo.setFocusable(true);
        txtCodigoConsulta.setEnabled(false);
        txtData.setEnabled(false);
        txtDescricao.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);
        limparForms();
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void limparForms(){
        txtCodigo.setText("");
        txtCodigoConsulta.setText("");
        txtData.setText("");
        txtDescricao.setText("");
        txtHorario.setText("");
        lblNomeMedico.setText("");
        txtValor.setText("");
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prepCon = new PreparaConexao("","");                          
        prepCon.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        
        prepCon.setConnectionString("jdbc:ucanaccess://C:\\\\Users\\\\LucasMorais\\\\Desktop\\\\Trabalhos POO\\\\src\\\\fatec\\\\poo\\\\basededados\\\\BDClinicaEricaLucasNicolas.accdb");
        daoExame = new DaoExame(prepCon.abrirConexao());
        daoConsulta = new DaoConsulta(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarConsultaActionPerformed
        int codConsulta = Integer.parseInt(txtCodigoConsulta.getText());
        consulta = daoConsulta.consultarConsulta(codConsulta);
        if(consulta==null){
           JOptionPane.showMessageDialog(null, "Consulta não cadastrada");
        }
        else{
            lblNomeMedico.setText(consulta.getMedico().getNome());
            txtCodigoConsulta.setEnabled(false);
            btnConsultarConsulta.setEnabled(false);
            txtDescricao.setEnabled(true);
            txtData.setEnabled(true);
            txtHorario.setEnabled(true);
            txtValor.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoConsulta;
    private javax.swing.JLabel lblCodigoConsulta1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoConsulta;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
